#program KTP

nik=input("Masukkan NIK: ")
nama=input("Masukkan Nama: ")
ttl=input("Masukkan TTL: ")
jk=input("Masukkan Jenis Kelamin: ")
alamat=input("Masukkan Alamat: ")
agama=input("Masukkan Agama: ")
statkawin=input("Masukkan Status Perkawinan: ")
pekerjaan=input("Masukkan Pekerjaan: ")
wn=input("Masukkan Kewarganegaraan: ")
berlaku=input("Masukkan Berlaku Hingga: ")
print("NIK			:{0}".format(nik))
print("Nama			:{0}".format(nama))
print("Tempat, Tanggal Lahir	:{0}".format(ttl))
print("Jenis Kelamin		:{0}".format(jk))
print("Alamat			:{0}".format(alamat))
print("Agama			:{0}".format(agama))
print("Status Perkawinan	:{0}".format(statkawin))
print("Pekerjaan		:{0}".format(pekerjaan))
print("Kewarganegaraan		:{0}".format(wn))
print("Berlaku Hingga		:{0}".format(berlaku))